project:
  type: website


website:
  title: "Uday's AI Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/UdiBhaskar

format:
  html:
    theme: cosmo
    # css: styles.css